###
GET http://localhost:80/subscription?userID=7 HTTP/1.1
###

###
POST http://localhost:80/subscription HTTP/1.1
Content-Type: application/json

{
    "userID" : 7,
    "subscription": {
        "serviceID": 112241,
        "settings": {
        "queuetime": 25,
        "distance": 5
        }
    }
}
###
POST http://localhost:80/subscriptions HTTP/1.1
Content-Type: application/json

{
    "userIDs" : [1,2,3]
}
###
DELETE  http://localhost:80/subscription?userID=7&serviceID=112241 HTTP/1.1
Content-Type: application/json



###
GET http://localhost:80/subscriptions?limit=1 HTTP/1.1

